# FROM nginx

# COPY index.html /usr/share/nginx/html
# # Install SSH server and configure
# RUN apt-get update && \
#     apt-get install -y openssh-server && \
#     mkdir /run/sshd && \
#     echo 'root:root' | chpasswd 
#     #useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 ubuntu && \
#     #echo 'ubuntu:password'| chpasswd && \
# RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#     sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
#     sed -i 's/Port 22/Port 4242/' /etc/ssh/sshd_config
# # Install tor and configure

# RUN apt-get install -y tor && \
#     echo "HiddenServiceDir /var/lib/tor/hidden_service/" >> /etc/tor/torrc && \
#     echo "HiddenServicePort 80 127.0.0.1:80" >> /etc/tor/torrc
# # RUN chown debian-tor:debian-tor /var/lib/tor/hidden_service/
# #RUN chmod 700 /var/lib/tor/hidden_service/

# # Generate host keys
# RUN ssh-keygen -A
# # Intall Tor and configure hidden service

# # Copy static website files to Nginx directory

# # Expose ports for HTTP and SSH
# EXPOSE 80
# EXPOSE 4242

# # Start SSH server and Nginx
# CMD ["/usr/sbin/sshd", "-D"] && service tor start && service ssh start && nginx -g 'daemon off;'
# FROM nginx
# RUN apt-get update && \
#     apt-get install -y tor
# COPY torrc /etc/tor/torrc
# COPY nginx.conf /etc/nginx/nginx.conf
# COPY index.html /usr/share/nginx/html/index.html
FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf

RUN apt-get update
RUN apt install -y tor

RUN apt-get install -y openssh-server && \
    mkdir /var/run/sshd && \
    echo 'root:password' | chpasswd
# Configure ssh server
# sd
COPY torrc /etc/tor/torrc
COPY sshd_config /etc/ssh/
#RUN ssh-keygen -A
RUN systemctl enable ssh
RUN tor -d
#RUN apt install -y iptables
EXPOSE 80 

EXPOSE 4242

EXPOSE 9050

CMD service tor start && nginx -g 'daemon off;' && ["/usr/sbin/sshd", "-D"]